import '../models/muffin.dart';

class MuffinSafetyPolicy {
  const MuffinSafetyPolicy();

  static const generalInstructions = [
    'Act as a supportive Form 2 learning companion.',
    'Use age-appropriate language.',
    'Stay within the current subject and chapter.',
    'Prefer guidance over direct answers.',
    'Ask short guiding questions where useful.',
    'Explain one step at a time.',
    'Avoid overwhelming the student.',
    'Use the student preferred language when requested.',
    'Clearly label generated questions as generated by Muffin.',
  ];

  static const quizInstructions = [
    'Never reveal the correct answer.',
    'Never name the correct answer option.',
    'Never say "Choose A/B/C/D".',
    'Never eliminate options in a way that exposes the answer.',
    'Never solve the entire question.',
    'Give conceptual or procedural guidance only.',
  ];

  static const allowedActions = {
    MuffinMode.learn: {
      MuffinAction.askMuffin,
      MuffinAction.explainSimply,
      MuffinAction.translate,
      MuffinAction.anotherExample,
      MuffinAction.stillConfused,
    },
    MuffinMode.practice: {
      MuffinAction.askMuffin,
      MuffinAction.smallHint,
      MuffinAction.explainConcept,
      MuffinAction.translate,
      MuffinAction.generateSimilarQuestion,
      MuffinAction.stillConfused,
    },
    MuffinMode.quiz: {
      MuffinAction.smallHint,
      MuffinAction.explainConcept,
      MuffinAction.translate,
      MuffinAction.identifyPattern,
      MuffinAction.guideQuestion,
    },
  };

  bool isAllowed(MuffinMode mode, MuffinAction action) {
    return allowedActions[mode]?.contains(action) ?? false;
  }

  String? refusalReason(MuffinRequest request) {
    if (!isAllowed(request.mode, request.action)) {
      return 'That Muffin action is not available on this screen.';
    }
    if (request.mode == MuffinMode.quiz &&
        request.action == MuffinAction.generateSimilarQuestion) {
      return 'During a quiz, Muffin can give hints but not create or reveal answers.';
    }
    return null;
  }

  MuffinResponse? validate(MuffinRequest request) {
    final reason = refusalReason(request);
    if (reason == null) return null;
    return MuffinResponse(
      responseType: MuffinResponseType.refusal,
      message: reason,
      suggestedNextAction: 'Try asking for a small hint instead.',
    );
  }
}
